# config.py

from pathlib import Path
from typing import List
from pydantic import BaseSettings, Field, validator

class Settings(BaseSettings):
    # ─── RSS feeds ───────────────────────────────────────────
    rss_feeds: List[str] = Field(
        [
            "https://www.404media.co/rss",
            "https://magazine.sebastianraschka.com/feed",
            "https://aiacceleratorinstitute.com/rss/",
            "https://ai-techpark.com/category/ai/feed/",
            "https://aibusiness.com/rss.xml",
            "https://aimodels.substack.com/feed",
            "https://www.artificialintelligence-news.com/feed/rss/",
            "https://venturebeat.com/category/ai/feed/",
            "https://ainowinstitute.org/category/news/feed",
            "https://www.reddit.com/r/aipromptprogramming/.rss",
            "https://siliconangle.com/category/ai/feed",
            "https://aisnakeoil.substack.com/feed",
            "https://eng.uber.com/category/articles/ai/feed",
            "https://www.anaconda.com/blog/feed",
            "https://analyticsindiamag.com/feed/",
            "https://stability.ai/blog?format=rss",
            "https://feeds.arstechnica.com/arstechnica/index",
            "https://www.reddit.com/r/artificial/.rss",
            "https://theconversation.com/europe/topics/artificial-intelligence-ai-90/articles.atom",
            "https://www.theguardian.com/technology/artificialintelligenceai/rss",
            "https://spacenews.com/tag/artificial-intelligence/feed/",
            "https://futurism.com/categories/ai-artificial-intelligence/feed",
            "https://www.wired.com/feed/tag/ai/latest/rss",
            "https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml",
            "https://www.techrepublic.com/rssfeeds/topic/artificial-intelligence/",
            "https://medium.com/feed/artificialis",
            "https://siliconangle.com/category/big-data/feed",
            "https://machinelearningmastery.com/blog/feed",
            "https://davidstutz.de/category/blog/feed",
            "https://www.together.xyz/blog?format=rss",
            "https://neptune.ai/blog/feed",
            "https://blog.eleuther.ai/index.xml",
            "https://pyimagesearch.com/blog/feed",
            "https://feeds.bloomberg.com/technology/news.rss",
            "https://feeds.businessinsider.com/custom/all",
            "https://www.wired.com/feed/category/business/latest/rss",
            "https://every.to/chain-of-thought/feed.xml",
            "https://huyenchip.com/feed",
            "https://www.reddit.com/r/computervision/.rss",
            "http://www.computerworld.com/index.rss",
            "https://txt.cohere.ai/rss/",
            "https://news.crunchbase.com/feed",
            "https://dagshub.com/blog/rss/",
            "https://www.darkreading.com/rss_simple.asp",
            "https://www.databricks.com/feed",
            "https://datafloq.com/feed/?post_type=post",
            "https://datamachina.substack.com/feed",
            "https://www.datanami.com/feed/",
            "https://www.reddit.com/r/datascience/.rss",
            "https://debuggercafe.com/feed/",
            "https://deephaven.io/blog/rss.xml",
            "https://www.reddit.com/r/deeplearning/.rss",
            "https://deepmind.com/blog/feed/basic/",
            "https://tech.eu/category/deep-tech/feed",
            "https://departmentofproduct.substack.com/feed",
            "https://dev.to/feed",
            "https://www.eetimes.com/feed",
            "https://www.engadget.com/rss.xml",
            "https://eugeneyan.com/rss/",
            "https://explosion.ai/feed",
            "https://www.freethink.com/feed/all",
            "https://www.generational.pub/feed",
            "https://www.forrester.com/blogs/category/artificial-intelligence-ai/feed",
            "https://www.ghacks.net/feed/",
            "https://gizmodo.com/rss",
            "https://globalnews.ca/tag/artificial-intelligence/feed",
            "http://googleaiblog.blogspot.com/atom.xml",
            "https://gradientflow.com/feed/",
            "https://hackernoon.com/tagged/ai/feed",
            "https://feeds.feedburner.com/HealthTechMagazine",
            "https://huggingface.co/blog/feed.xml",
            "https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss",
            "https://feed.infoq.com/ai-ml-data-eng/",
            "https://www.infoworld.com/category/analytics/index.rss",
            "https://www.infoworld.com/category/machine-learning/index.rss",
            "https://insidebigdata.com/feed",
            "https://www.interconnects.ai/feed",
            "https://www.ibtimes.com/rss",
            "https://www.jmlr.org/jmlr.xml",
            "https://www.kdnuggets.com/feed",
            "https://blog.langchain.dev/rss/",
            "https://lastweekin.ai/feed",
            "https://www.latent.space/feed",
            "https://sifted.eu/feed/?post_type=article",
            "https://www.zdnet.com/topic/artificial-intelligence/rss.xml",
            "https://www.zdnet.com/topic/big-data/rss.xml",
            "https://lightning.ai/pages/feed/",
            "https://www.reddit.com/r/MachineLearning/.rss",
            "https://www.bmc.com/blogs/categories/machine-learning-big-data/feed",
            "https://blog.ml.cmu.edu/feed",
            "https://www.nature.com/subjects/machine-learning.rss",
            "https://www.reddit.com/r/machinelearningnews/.rss",
            "https://www.microsoft.com/en-us/research/feed/",
            "https://mila.quebec/en/feed/",
            "https://news.mit.edu/rss/feed",
            "https://www.technologyreview.com/feed/",
            "https://foundation.mozilla.org/en/blog/rss/",
            "https://www.reddit.com/r/LanguageTechnology/.rss",
            "https://www.sciencedaily.com/rss/computers_math/neural_interfaces.xml",
            "https://www.reddit.com/r/neuralnetworks/.rss",
            "https://www.newscientist.com/subject/technology/feed/",
            "https://phys.org/rss-feed/technology-news/machine-learning-ai/",
            "https://techxplore.com/rss-feed/machine-learning-ai-news/",
            "https://www.assemblyai.com/blog/rss/",
            "https://nicholas.carlini.com/writing/feed.xml",
            "https://developer.nvidia.com/blog/feed",
            "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
            "https://www.oneusefulthing.org/feed",
            "https://openai.com/blog/rss/",
            "https://blog.paperspace.com/rss/",
            "https://petapixel.com/feed",
            "https://www.philschmid.de/feed.xml",
            "https://erichartford.com/rss.xml",
            "https://minimaxir.com/post/index.xml",
            "https://www.producthunt.com/feed",
            "https://feeds.feedburner.com/PythonInsider",
            "https://api.quantamagazine.org/feed",
            "https://medium.com/feed/radix-ai-blog",
            "https://feeds.feedburner.com/RBloggers",
            "https://replicate.com/blog/rss",
            "https://notes.replicatecodex.com/rss/",
            "https://restofworld.org/feed/latest",
            "https://www.sciencedaily.com/rss/computers_math/robotics.xml",
            "https://tech.eu/category/robotics/feed",
            "http://rss.sciam.com/ScientificAmerican-Global",
            "https://www.semianalysis.com/feed",
            "https://www.siliconrepublic.com/feed",
            "https://simonwillison.net/atom/everything/",
            "https://stackoverflow.blog/feed/",
            "https://crfm.stanford.edu/feed",
            "https://medium.com/feed/@netflixtechblog",
            "https://medium.com/feed/@odsc",
            "https://syncedreview.com/feed",
            "https://synthedia.substack.com/feed",
            "https://techcrunch.com/feed/",
            "https://www.techmeme.com/feed.xml",
            "https://techmonitor.ai/feed",
            "https://www.reutersagency.com/feed/?best-topics=tech",
            "https://www.techspot.com/backend.xml",
            "https://bdtechtalks.com/feed/",
            "https://thealgorithmicbridge.substack.com/feed",
            "https://bair.berkeley.edu/blog/feed.xml",
            "https://the-decoder.com/feed/",
            "https://thegradient.pub/rss/",
            "https://www.theinformation.com/feed",
            "https://www.theintrinsicperspective.com/feed/",
            "https://thenewstack.io/feed",
            "https://thenextweb.com/neural/feed",
            "https://www.theregister.com/software/ai_ml/headlines.atom",
            "https://rss.beehiiv.com/feeds/2R3C6Bt5wj.xml",
            "https://thesequence.substack.com/feed",
            "https://www.thestack.technology/latest/rss/",
            "https://blog.tensorflow.org/feeds/posts/default?alt=rss",
            "https://www.thetradenews.com/feed/",
            "https://www.theverge.com/rss/index.xml",
            "http://feeds.libsyn.com/102459/rss",
            "https://pub.towardsai.net/feed",
            "https://towardsdatascience.com/feed",
            "https://www.unite.ai/feed/",
            "https://unwindai.substack.com/feed",
            "https://www.vice.com/en/rss/topic/ai",
            "https://visualstudiomagazine.com/rss-feeds/news.aspx",
            "https://voicebot.ai/feed/",
            "https://wandb.ai/fully-connected/rss.xml",
            "https://blogs.windows.com/feed",
            "https://blog.wolfram.com/feed/",
            "https://aihub.org/feed?cat=-473",
            "https://topenddevs.com/podcasts/adventures-in-machine-learning/rss.rss",
            "https://aiandbanking.libsyn.com/rss",
            "https://feeds.blubrry.com/feeds/aitoday.xml",
            "https://feeds.acast.com/public/shows/e421d786-ec36-4148-aa99-7a3b2928a779",
            "https://www.dataengineeringpodcast.com/feed/mp3/",
            "https://datascienceathome.com/feed.xml",
            "https://dataskeptic.libsyn.com/rss",
            "https://datastori.es/feed/",
            "https://anchor.fm/s/41286f68/podcast/rss",
            "https://www.thechatgptreport.com/episodes?format=rss",
            "https://aneyeonai.libsyn.com/rss",
            "https://geomob-podcast.castos.com/feed",
            "https://anchor.fm/s/443868ac/podcast/rss",
            "https://feeds.captivate.fm/gradient-dissent/",
            "https://feed.podbean.com/hdsr/feed.xml",
            "https://anchor.fm/s/174cb1b8/podcast/rss",
            "http://feeds.soundcloud.com/users/soundcloud:users:306749289/sounds.rss",
            "http://nssdeviations.com/rss",
            "https://feeds.transistor.fm/postgres-fm",
            "https://changelog.com/practicalai/feed",
            "http://lexisnexisbis.libsyn.com/rss",
            "https://talkpython.fm/episodes/rss",
            "https://feeds.libsyn.com/468519/rss",
            "http://podcast.emerj.com/rss",
            "http://feeds.soundcloud.com/users/soundcloud:users:264034133/sounds.rss",
            "https://anchor.fm/s/3952c6f8/podcast/rss",
            "https://feeds.fireside.fm/theartistsofdatascience/rss",
            "https://feeds.transistor.fm/the-data-engineering-show",
            "https://thedataexchange.media/feed/",
            "https://api.substack.com/feed/podcast/265424/s/1354.rss",
            "https://www.themachinelearningpodcast.com/rss",
            "https://feeds.megaphone.fm/marketingai",
            "https://twimlai.com/feed",
            "https://feeds.transistor.fm/this-day-in-ai",
            "https://anchor.fm/s/32ec7408/podcast/rss",
            "https://www.youtube.com/feeds/videos.xml?channel_id=UCpV_X0VrL8-jg3t6wYGS-1g",
        ],
        description="List of RSS feed URLs to scrape for articles",
    )

    # ─── Classification ──────────────────────────────────────
    topic_labels: List[str] = Field(
        [
            "AI in business",
            "AI in research",
            "AI in development",
            "AI in healthcare",
            "AI in finance",
            "AI in education",  
            "AI in manufacturing",
            "AI in transportation",
        ],
        description="Labels for zero-shot classification",
    )
    threshold: float = Field(
        0.5, ge=0.0, le=1.0, description="Minimum confidence to assign a topic"
    )

    # ─── Discord Bot ─────────────────────────────────────────
    discord_bot_token: str = Field(
        ..., env="DISCORD_BOT_TOKEN", description="Discord bot token"
    )
    discord_channel_id: int = Field(
        ..., env="DISCORD_CHANNEL_ID", description="Channel ID to post into"
    )

    # ─── .env file support ────────────────────────────────────
    env_file: Path = Path(".env")
    env_file_encoding: str = "utf-8"

    @validator("rss_feeds", each_item=True)
    def must_be_valid_url(cls, v):
        if not v.startswith(("http://", "https://")):
            raise ValueError(f"Invalid RSS URL: {v!r}")
        return v

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"


# Instantiate and validate settings
settings = Settings()
